/**
 * The Superhealth design system, read out of the Figma file.
 *
 * Generated by decoding Superhealth Design system.fig — a zip whose canvas.fig
 * is Kiwi-encoded (deflate for the schema, Zstandard for the document). Every
 * value here comes from that file; nothing is authored by hand, which is why
 * the odd names and the one "Component 261" are left as they are.
 *
 * Two libraries referenced by the file but belonging to other projects are
 * filtered out, since including them would misrepresent this system.
 */

export interface Swatch {
  name: string
  scheme: string | null
  group: string | null
  token: string
  hex: string
  alpha: number
  luminance: number
  note: string | null
}

export interface TypeStyle {
  name: string
  role: string | null
  family: string | null
  style: string | null
  size: number | null
  lineHeight: { value: number; units: string } | null
  letterSpacing: { value: number; units: string } | null
  token: string
}

export interface EffectStyle {
  name: string
  layers: { type: string; x: number; y: number; radius: number; spread: number; color: string | null; alpha: number | null }[]
}

export interface Token {
  name: string
  group: string | null
  sub: string | null
  token: string
  resolvedType: string | null
  set: string | null
  value: string | number | boolean | null
}

export interface ComponentSet {
  name: string
  internal: boolean
  variants: number
  props: { prop: string; values: string[] }[]
}

export const system = {
  "counts": {
    "nodes": 14423,
    "colours": 18,
    "type": 30,
    "effects": 6,
    "variables": 58,
    "componentFamilies": 49,
    "componentVariants": 2799,
    "instances": 2370
  },
  "colours": [
    {
      "name": "light/gray/gray-50",
      "scheme": "light",
      "group": "gray",
      "token": "gray-50",
      "hex": "#FFFFFF",
      "alpha": 1,
      "luminance": 1,
      "note": "Contrast with gray-100: -1.07"
    },
    {
      "name": "light/gray/gray-800",
      "scheme": "light",
      "group": "gray",
      "token": "gray-800",
      "hex": "#222222",
      "alpha": 1,
      "luminance": 0.016,
      "note": "Contrast with gray-100: 14.96"
    },
    {
      "name": "light/gray/gray-900",
      "scheme": "light",
      "group": "gray",
      "token": "gray-900",
      "hex": "#000000",
      "alpha": 1,
      "luminance": 0,
      "note": "Contrast with gray-100: 19.78"
    },
    {
      "name": "Orange / 400",
      "scheme": "Orange ",
      "group": null,
      "token": " 400",
      "hex": "#F07F23",
      "alpha": 1,
      "luminance": 0.3383,
      "note": null
    },
    {
      "name": "Red / 600",
      "scheme": "Red ",
      "group": null,
      "token": " 600",
      "hex": "#BD002A",
      "alpha": 1,
      "luminance": 0.1099,
      "note": null
    },
    {
      "name": "Green / 600",
      "scheme": "Green ",
      "group": null,
      "token": " 600",
      "hex": "#006D23",
      "alpha": 1,
      "luminance": 0.1106,
      "note": null
    },
    {
      "name": "Blue / 600",
      "scheme": "Blue ",
      "group": null,
      "token": " 600",
      "hex": "#0059C8",
      "alpha": 1,
      "luminance": 0.1131,
      "note": null
    },
    {
      "name": "Grey/600",
      "scheme": "Grey",
      "group": null,
      "token": "600",
      "hex": "#5A657C",
      "alpha": 1,
      "luminance": 0.1294,
      "note": null
    },
    {
      "name": "White",
      "scheme": null,
      "group": null,
      "token": "White",
      "hex": "#FFFFFF",
      "alpha": 1,
      "luminance": 1,
      "note": null
    },
    {
      "name": "Grey/900",
      "scheme": "Grey",
      "group": null,
      "token": "900",
      "hex": "#111B2B",
      "alpha": 1,
      "luminance": 0.0108,
      "note": null
    },
    {
      "name": "Grey / 800",
      "scheme": "Grey ",
      "group": null,
      "token": " 800",
      "hex": "#1B273A",
      "alpha": 1,
      "luminance": 0.0199,
      "note": null
    },
    {
      "name": "Grey/700",
      "scheme": "Grey",
      "group": null,
      "token": "700",
      "hex": "#414D63",
      "alpha": 1,
      "luminance": 0.0733,
      "note": null
    },
    {
      "name": "Grey/200",
      "scheme": "Grey",
      "group": null,
      "token": "200",
      "hex": "#E7EBEE",
      "alpha": 1,
      "luminance": 0.8258,
      "note": null
    },
    {
      "name": "Dark",
      "scheme": null,
      "group": null,
      "token": "Dark",
      "hex": "#141B34",
      "alpha": 1,
      "luminance": 0.0118,
      "note": null
    },
    {
      "name": "Grey 500",
      "scheme": null,
      "group": null,
      "token": "Grey 500",
      "hex": "#667085",
      "alpha": 1,
      "luminance": 0.1611,
      "note": null
    },
    {
      "name": "State/Red-0",
      "scheme": "State",
      "group": null,
      "token": "Red-0",
      "hex": "#F65353",
      "alpha": 1,
      "luminance": 0.2632,
      "note": null
    },
    {
      "name": "Base/Primary",
      "scheme": "Base",
      "group": null,
      "token": "Primary",
      "hex": "#061720",
      "alpha": 1,
      "luminance": 0.0076,
      "note": null
    },
    {
      "name": "Content/Yellow-1",
      "scheme": "Content",
      "group": null,
      "token": "Yellow-1",
      "hex": "#D98D15",
      "alpha": 1,
      "luminance": 0.339,
      "note": null
    }
  ],
  "type": [
    {
      "name": "heading/serif/desktop/heavy/heading-xxl-heavy",
      "role": "heading",
      "family": "Source Serif Pro",
      "style": "Bold",
      "size": 45,
      "lineHeight": {
        "value": 100,
        "units": "PERCENT"
      },
      "letterSpacing": {
        "value": 0,
        "units": "PERCENT"
      },
      "token": "heading-xxl-heavy"
    },
    {
      "name": "Superhealth/Mobile/Body S",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body S"
    },
    {
      "name": "Superhealth/Mobile/Body M",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 16,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body M"
    },
    {
      "name": "Superhealth/Mobile/Label",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 12,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Label"
    },
    {
      "name": "Paragraph/Normal",
      "role": "Paragraph",
      "family": "Work Sans",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 20,
        "units": "PIXELS"
      },
      "letterSpacing": {
        "value": -0.15,
        "units": "PIXELS"
      },
      "token": "Normal"
    },
    {
      "name": "Superhealth/Mobile/H1",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 48,
      "lineHeight": {
        "value": 1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H1"
    },
    {
      "name": "Superhealth/Mobile/H4",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Semibold",
      "size": 28,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H4"
    },
    {
      "name": "Superhealth/Mobile/Body XL",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 24,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body XL"
    },
    {
      "name": "Superhealth/Desktop/Body S",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 16,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body S"
    },
    {
      "name": "Superhealth/Mobile/H2",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 40,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H2"
    },
    {
      "name": "Superhealth/Mobile/H3",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 32,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H3"
    },
    {
      "name": "Superhealth/Mobile/H5",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Semibold",
      "size": 20,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H5"
    },
    {
      "name": "Superhealth/Mobile/H6",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Semibold",
      "size": 16,
      "lineHeight": {
        "value": 1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": 0,
        "units": "PERCENT"
      },
      "token": "H6"
    },
    {
      "name": "Superhealth/Mobile/Body L",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 20,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body L"
    },
    {
      "name": "Body Caps Bold",
      "role": "Body Caps Bold",
      "family": "Graphik Web",
      "style": "Semibold",
      "size": 14,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": 0,
        "units": "PERCENT"
      },
      "token": "Body Caps Bold"
    },
    {
      "name": "Body caps",
      "role": "Body caps",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": 0,
        "units": "PERCENT"
      },
      "token": "Body caps"
    },
    {
      "name": "Superhealth/Mobile/Caption",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Caption"
    },
    {
      "name": "Superhealth/Mobile/Link",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 12,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Link"
    },
    {
      "name": "Superhealth/Desktop/Display",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 60,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Display"
    },
    {
      "name": "Superhealth/Desktop/H1",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 56,
      "lineHeight": {
        "value": 1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H1"
    },
    {
      "name": "Superhealth/Desktop/H2",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Bold",
      "size": 40,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H2"
    },
    {
      "name": "Superhealth/Desktop/H3",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Semibold",
      "size": 28,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "H3"
    },
    {
      "name": "Superhealth/Desktop/Body XL",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 28,
      "lineHeight": {
        "value": 1.1,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body XL"
    },
    {
      "name": "Superhealth/Desktop/Body L",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 24,
      "lineHeight": {
        "value": 1.2,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body L"
    },
    {
      "name": "Superhealth/Desktop/Body M",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 18,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body M"
    },
    {
      "name": "Superhealth/Desktop/Caption",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Caption"
    },
    {
      "name": "Superhealth/Desktop/Link",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Link"
    },
    {
      "name": ".Label",
      "role": ".Label",
      "family": "SF Mono",
      "style": "Regular",
      "size": 13,
      "lineHeight": {
        "value": 20,
        "units": "PIXELS"
      },
      "letterSpacing": {
        "value": 0,
        "units": "PIXELS"
      },
      "token": ".Label"
    },
    {
      "name": "Superhealth/Link/Medium",
      "role": "Superhealth",
      "family": "Circular Std",
      "style": "Medium",
      "size": 12,
      "lineHeight": {
        "value": 1.5,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Medium"
    },
    {
      "name": "Superhealth/Mobile/Body S",
      "role": "Superhealth",
      "family": "Graphik Web",
      "style": "Regular",
      "size": 14,
      "lineHeight": {
        "value": 1.4,
        "units": "RAW"
      },
      "letterSpacing": {
        "value": -2,
        "units": "PERCENT"
      },
      "token": "Body S"
    }
  ],
  "effects": [
    {
      "name": "Focused glow/Primary",
      "layers": [
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 0,
          "radius": 0,
          "spread": 3,
          "color": "#AFD6FF",
          "alpha": 1
        }
      ]
    },
    {
      "name": "Focused glow/Negative",
      "layers": [
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 0,
          "radius": 0,
          "spread": 3,
          "color": "#FFB1B2",
          "alpha": 1
        }
      ]
    },
    {
      "name": "Shadow/Button",
      "layers": [
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 1,
          "radius": 0,
          "spread": 0,
          "color": "#111B2B",
          "alpha": 0.05
        }
      ]
    },
    {
      "name": "Shadow/Default",
      "layers": [
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 6,
          "radius": 12,
          "spread": -2,
          "color": "#192532",
          "alpha": 0.1
        },
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 3,
          "radius": 7,
          "spread": -3,
          "color": "#192532",
          "alpha": 0.1
        },
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 0,
          "radius": 0,
          "spread": 1,
          "color": "#192532",
          "alpha": 0.1
        }
      ]
    },
    {
      "name": "Shadow/Heavy",
      "layers": [
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 13,
          "radius": 27,
          "spread": -5,
          "color": "#192532",
          "alpha": 0.15
        },
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 8,
          "radius": 16,
          "spread": -8,
          "color": "#192532",
          "alpha": 0.2
        },
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": -6,
          "radius": 16,
          "spread": -6,
          "color": "#192532",
          "alpha": 0.03
        },
        {
          "type": "DROP_SHADOW",
          "x": 0,
          "y": 0,
          "radius": 0,
          "spread": 1,
          "color": "#192532",
          "alpha": 0.1
        }
      ]
    },
    {
      "name": "Inner Shadow/Default",
      "layers": [
        {
          "type": "INNER_SHADOW",
          "x": 0,
          "y": 2,
          "radius": 0,
          "spread": 0,
          "color": "#E7EBEE",
          "alpha": 0.2
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Colours/Grey/Grey 300",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 300",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#BCBCBC"
    },
    {
      "name": "Colours/Solid/White",
      "group": "Colours",
      "sub": "Solid",
      "token": "White",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#FFFFFF"
    },
    {
      "name": "Stroke/Focused",
      "group": "Stroke",
      "sub": null,
      "token": "Focused",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#AFD6FF"
    },
    {
      "name": "Brand Colours/Precious Blue",
      "group": "Brand Colours",
      "sub": null,
      "token": "Precious Blue",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#1F30A0"
    },
    {
      "name": "Brand Colours/Fantasia Purple",
      "group": "Brand Colours",
      "sub": null,
      "token": "Fantasia Purple",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#914BFA"
    },
    {
      "name": "Brand Colours/Pearl Black",
      "group": "Brand Colours",
      "sub": null,
      "token": "Pearl Black",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#2F2F2F"
    },
    {
      "name": "Brand Colours/Spring Wood",
      "group": "Brand Colours",
      "sub": null,
      "token": "Spring Wood",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#F9F7F3"
    },
    {
      "name": "Brand Colours/White",
      "group": "Brand Colours",
      "sub": null,
      "token": "White",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#FFFFFF"
    },
    {
      "name": "Colours/Blue/Blue 100",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 100",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#EAECFB"
    },
    {
      "name": "Colours/Blue/Blue 200",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 200",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#B8C0F1"
    },
    {
      "name": "Colours/Blue/Blue 300",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 300",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#8794E8"
    },
    {
      "name": "Colours/Blue/Blue 400",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 400",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#5668DE"
    },
    {
      "name": "Colours/Blue/Blue 500",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 500",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#293FD1"
    },
    {
      "name": "Colours/Blue/Blue 600",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 600",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#1F30A0"
    },
    {
      "name": "Colours/Blue/Blue 700",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 700",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#162272"
    },
    {
      "name": "Colours/Blue/Blue 800",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 800",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#0D1444"
    },
    {
      "name": "Colours/Blue/Blue 900",
      "group": "Colours",
      "sub": "Blue",
      "token": "Blue 900",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#040615"
    },
    {
      "name": "Colours/Purple/Purpule 100",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 100",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#F0E6FE"
    },
    {
      "name": "Colours/Purple/Purpule 200",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 200",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#D0B2FD"
    },
    {
      "name": "Colours/Purple/Purpule 300",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 300",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#B17FFB"
    },
    {
      "name": "Colours/Purple/Purpule 400",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 400",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#914BFA"
    },
    {
      "name": "Colours/Purple/Purpule 500",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 500",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#6D11F8"
    },
    {
      "name": "Colours/Purple/Purpule 600",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 600",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#5306C8"
    },
    {
      "name": "Colours/Purple/Purpule 700",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 700",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#3B048D"
    },
    {
      "name": "Colours/Purple/Purpule 800",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 800",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#230253"
    },
    {
      "name": "Colours/Purple/Purpule 900",
      "group": "Colours",
      "sub": "Purple",
      "token": "Purpule 900",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#0A0119"
    },
    {
      "name": "Colours/Grey/Grey 100",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 100",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#F2F2F2"
    },
    {
      "name": "Colours/Grey/Grey 200",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 200",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#D7D7D7"
    },
    {
      "name": "Colours/Grey/Grey 400",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 400",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#A1A1A1"
    },
    {
      "name": "Colours/Grey/Grey 500",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 500",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#868686"
    },
    {
      "name": "Colours/Grey/Grey 600",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 600",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#6A6A6A"
    },
    {
      "name": "Colours/Grey/Grey 700",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 700",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#4F4F4F"
    },
    {
      "name": "Colours/Grey/Grey 800",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 800",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#343434"
    },
    {
      "name": "Colours/Grey/Grey 900",
      "group": "Colours",
      "sub": "Grey",
      "token": "Grey 900",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#191919"
    },
    {
      "name": "Colours/Solid/Black",
      "group": "Colours",
      "sub": "Solid",
      "token": "Black",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#000000"
    },
    {
      "name": "Colours/Solid/Black transparent",
      "group": "Colours",
      "sub": "Solid",
      "token": "Black transparent",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#000000"
    },
    {
      "name": "Colours/Solid/White transparent",
      "group": "Colours",
      "sub": "Solid",
      "token": "White transparent",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#FFFFFF"
    },
    {
      "name": "Schemes/Error",
      "group": "Schemes",
      "sub": null,
      "token": "Error",
      "resolvedType": "COLOR",
      "set": "M3",
      "value": "#B3261E"
    },
    {
      "name": "3XL",
      "group": null,
      "sub": null,
      "token": "3XL",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 64
    },
    {
      "name": "2XL",
      "group": null,
      "sub": null,
      "token": "2XL",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 48
    },
    {
      "name": "XL",
      "group": null,
      "sub": null,
      "token": "XL",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 32
    },
    {
      "name": "L",
      "group": null,
      "sub": null,
      "token": "L",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 24
    },
    {
      "name": "M",
      "group": null,
      "sub": null,
      "token": "M",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 16
    },
    {
      "name": "S",
      "group": null,
      "sub": null,
      "token": "S",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 12
    },
    {
      "name": "XS",
      "group": null,
      "sub": null,
      "token": "XS",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 8
    },
    {
      "name": "2XS",
      "group": null,
      "sub": null,
      "token": "2XS",
      "resolvedType": "FLOAT",
      "set": "Spacing Tokens",
      "value": 4
    },
    {
      "name": "Spacing/2XS",
      "group": "Spacing",
      "sub": null,
      "token": "2XS",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 4
    },
    {
      "name": "Spacing/3XL",
      "group": "Spacing",
      "sub": null,
      "token": "3XL",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 64
    },
    {
      "name": "Spacing/4XL",
      "group": "Spacing",
      "sub": null,
      "token": "4XL",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 80
    },
    {
      "name": "Spacing/XS",
      "group": "Spacing",
      "sub": null,
      "token": "XS",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 8
    },
    {
      "name": "Spacing/S",
      "group": "Spacing",
      "sub": null,
      "token": "S",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 12
    },
    {
      "name": "Spacing/M",
      "group": "Spacing",
      "sub": null,
      "token": "M",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 16
    },
    {
      "name": "Spacing/L",
      "group": "Spacing",
      "sub": null,
      "token": "L",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 24
    },
    {
      "name": "Spacing/XL",
      "group": "Spacing",
      "sub": null,
      "token": "XL",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 32
    },
    {
      "name": "Spacing/2XL",
      "group": "Spacing",
      "sub": null,
      "token": "2XL",
      "resolvedType": "FLOAT",
      "set": "Superhealth",
      "value": 48
    },
    {
      "name": "Miscellaneous/Alert, Menu, Action Sheet - Separators",
      "group": "Miscellaneous",
      "sub": null,
      "token": "Alert, Menu, Action Sheet - Separators",
      "resolvedType": "COLOR",
      "set": "System Colors",
      "value": "#808080"
    },
    {
      "name": "Supercolor/Primary/Precious_Blue",
      "group": "Supercolor",
      "sub": "Primary",
      "token": "Precious_Blue",
      "resolvedType": "COLOR",
      "set": "Superhealth",
      "value": "#1F30A0"
    },
    {
      "name": "Miscellaneous/Floating Tab - Text Unselected",
      "group": "Miscellaneous",
      "sub": null,
      "token": "Floating Tab - Text Unselected",
      "resolvedType": "COLOR",
      "set": "System Colors",
      "value": "#090909"
    }
  ],
  "components": [
    {
      "name": "Icon",
      "internal": false,
      "variants": 1904,
      "props": [
        {
          "prop": "Color",
          "values": [
            "Muted",
            "Negative",
            "Positive",
            "Primary",
            "Secondary",
            "Warning",
            "White"
          ]
        },
        {
          "prop": "Icon",
          "values": [
            "Arrow Down",
            "Arrow Up",
            "ArrowBackward",
            "ArrowForward",
            "Asset",
            "Bin",
            "Calendar",
            "Chat bubble",
            "CheckCircle",
            "Checkmark",
            "Chevron Right",
            "Chevron left",
            "ChevronDown",
            "ChevronUp",
            "Close",
            "Code",
            "Copy",
            "Cycle",
            "Delete",
            "Download",
            "Draggable",
            "Edit",
            "Entry",
            "Error Circle Outline",
            "ErrorCircle",
            "External Link",
            "Eye",
            "Face Happy",
            "Folder",
            "Folder Create",
            "Folder Open",
            "Format Bold",
            "Format Italic",
            "Format Underlined",
            "Heading",
            "Heading One",
            "Heading Two",
            "Help Circle",
            "Horizontal Rule",
            "InfoCircle",
            "Link",
            "List Bulleted",
            "List Numbered",
            "Loading",
            "Lock",
            "Logout",
            "Menu",
            "More",
            "More Horizontal",
            "More Vertical",
            "Plus",
            "Plus Circle",
            "Puzzle",
            "Quote",
            "Receipt",
            "Reference",
            "Resize",
            "Search",
            "Settings",
            "Shopping Cart",
            "Star",
            "Text",
            "Thumb Down",
            "Thumb Up",
            "Toggle",
            "TriangleOutline",
            "Users",
            "Warning"
          ]
        },
        {
          "prop": "Size",
          "values": [
            "Large",
            "Medium",
            "Small",
            "Tiny"
          ]
        }
      ]
    },
    {
      "name": "Text field",
      "internal": false,
      "variants": 408,
      "props": [
        {
          "prop": "Button",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "country type",
          "values": [
            "Code",
            "Flag"
          ]
        },
        {
          "prop": "Error",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Label",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Required",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "State",
          "values": [
            "Active",
            "Default",
            "Disabled"
          ]
        },
        {
          "prop": "Type",
          "values": [
            "Empty",
            "Placeholder",
            "Text"
          ]
        }
      ]
    },
    {
      "name": "Select field",
      "internal": false,
      "variants": 96,
      "props": [
        {
          "prop": "Error",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Help Text",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Label",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Required",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "State",
          "values": [
            "Active",
            "Default",
            "Disabled"
          ]
        }
      ]
    },
    {
      "name": "Buttons",
      "internal": false,
      "variants": 70,
      "props": [
        {
          "prop": "Focused",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Size",
          "values": [
            "Large",
            "Small"
          ]
        },
        {
          "prop": "State",
          "values": [
            "Active",
            "Default",
            "Disabled",
            "Hover"
          ]
        },
        {
          "prop": "Type",
          "values": [
            "Hero",
            "Primary",
            "Secondary"
          ]
        }
      ]
    },
    {
      "name": ".IconBase",
      "internal": true,
      "variants": 69,
      "props": [
        {
          "prop": "Name",
          "values": [
            "Arrow Down",
            "ArrowBackward",
            "ArrowForward",
            "ArrowUp",
            "Asset",
            "Bin",
            "Calendar",
            "ChatBubble",
            "CheckCircle",
            "Checkmark",
            "Chevron Down",
            "Chevron Left",
            "Chevron Right",
            "Chevron Up",
            "Close",
            "Code",
            "Copy",
            "Cycle",
            "Delete",
            "Download",
            "Drag",
            "Edit",
            "Entry",
            "Error Circle Outline",
            "ErrorCircle",
            "External Link",
            "Eye",
            "Face Happy",
            "Filter",
            "Folder",
            "Folder Create",
            "Folder Open",
            "Format Bold",
            "Format Italic",
            "Format Underlined",
            "Heading",
            "Heading One",
            "Heading Two",
            "Help Circle",
            "Horizontal Rule",
            "InfoCircle",
            "Link",
            "List Bulleted",
            "List Numbered",
            "Loading",
            "Lock",
            "Logout",
            "Menu",
            "More",
            "More Horizontal",
            "More Vertical",
            "Plus",
            "Plus Circle",
            "Puzzle",
            "Quote",
            "Receipt",
            "Reference",
            "Resize",
            "Search",
            "Settings",
            "Shopping Cart",
            "Star",
            "Text",
            "Thumb Down",
            "Thumb Up",
            "Toggle",
            "TriangleOutline",
            "Users",
            "Warning"
          ]
        }
      ]
    },
    {
      "name": "Website Components",
      "internal": false,
      "variants": 44,
      "props": []
    },
    {
      "name": "OTP Input Field",
      "internal": false,
      "variants": 24,
      "props": [
        {
          "prop": "Error",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Resend link",
          "values": [
            "Countdown",
            "False",
            "Resend"
          ]
        },
        {
          "prop": "Type",
          "values": [
            "Code",
            "Empty"
          ]
        }
      ]
    },
    {
      "name": "Spacing",
      "internal": false,
      "variants": 18,
      "props": [
        {
          "prop": "Property 1",
          "values": [
            "Default",
            "Variant2",
            "Variant3",
            "Variant4",
            "Variant5",
            "Variant6",
            "Variant7",
            "Variant8",
            "Variant9"
          ]
        }
      ]
    },
    {
      "name": "Label Pill",
      "internal": false,
      "variants": 16,
      "props": [
        {
          "prop": "Mode",
          "values": [
            "Dark",
            "Light"
          ]
        },
        {
          "prop": "Responsive",
          "values": [
            "Desktop",
            "Mobile"
          ]
        },
        {
          "prop": "Variant",
          "values": [
            "Active",
            "Inactive"
          ]
        }
      ]
    },
    {
      "name": "Component 261",
      "internal": false,
      "variants": 16,
      "props": [
        {
          "prop": "Focus",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Size",
          "values": [
            "Desktop",
            "Mobile"
          ]
        },
        {
          "prop": "Variant",
          "values": [
            "Default",
            "Satellite"
          ]
        }
      ]
    },
    {
      "name": "Logotype and Mark",
      "internal": false,
      "variants": 14,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Superhealth Fav Icon - 1200x1200",
            "Superhealth Fav Icon - 128x128",
            "Superhealth Fav Icon - 24x24",
            "Superhealth Fav Icon - 32x32",
            "Superhealth Fav Icon - 48x48",
            "Superhealth Logo White",
            "Superhealth logo"
          ]
        }
      ]
    },
    {
      "name": "play",
      "internal": false,
      "variants": 9,
      "props": [
        {
          "prop": "Style",
          "values": [
            "Bulk",
            "Duotone",
            "Solid",
            "Stroke",
            "Twotone"
          ]
        },
        {
          "prop": "Type",
          "values": [
            "Rounded",
            "Sharp",
            "Standard"
          ]
        }
      ]
    },
    {
      "name": "Appointment Cards",
      "internal": false,
      "variants": 8,
      "props": [
        {
          "prop": "Property 1",
          "values": [
            "Consultation card",
            "Event card (Offline)",
            "Event card (online)",
            "Test and scans"
          ]
        }
      ]
    },
    {
      "name": "Date selector pills",
      "internal": false,
      "variants": 8,
      "props": [
        {
          "prop": "Selected",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Today",
          "values": [
            "False",
            "True"
          ]
        }
      ]
    },
    {
      "name": "Frequently Asked Questions",
      "internal": false,
      "variants": 8,
      "props": [
        {
          "prop": "Break",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Variant",
          "values": [
            "Expanded",
            "Normal"
          ]
        }
      ]
    },
    {
      "name": "Radio + text",
      "internal": false,
      "variants": 6,
      "props": [
        {
          "prop": "State",
          "values": [
            "Selected",
            "Unselected"
          ]
        },
        {
          "prop": "Text",
          "values": [
            "False",
            "True"
          ]
        },
        {
          "prop": "Text align",
          "values": [
            "Left",
            "NA",
            "Right"
          ]
        }
      ]
    },
    {
      "name": "Component 259",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Property 1",
          "values": [
            "Frame 1820596758",
            "Frame 1820596759"
          ]
        }
      ]
    },
    {
      "name": "Component 260",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Mobile Navbar",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "State",
          "values": [
            "Default",
            "Expanded"
          ]
        }
      ]
    },
    {
      "name": "Desktop Navbar",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "State",
          "values": [
            "Default",
            "Logged in"
          ]
        }
      ]
    },
    {
      "name": "Infographic 1",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Infographic 2",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Video Testimonial Card 1",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Video Testimonial Carousel 1",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variants",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Content Cards",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Content Carousel",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Footer",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Reports card",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "State",
          "values": [
            "Uploaded",
            "Uploading"
          ]
        },
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Button - Slot Booking",
      "internal": false,
      "variants": 4,
      "props": [
        {
          "prop": "State",
          "values": [
            "Book",
            "No slots"
          ]
        },
        {
          "prop": "Variant",
          "values": [
            "Desktop",
            "Mobile"
          ]
        }
      ]
    },
    {
      "name": "Mobile Card Button",
      "internal": false,
      "variants": 3,
      "props": [
        {
          "prop": "Property 1",
          "values": [
            "Disable",
            "Primary",
            "Secondary"
          ]
        }
      ]
    },
    {
      "name": "Desk Booking Card Button",
      "internal": false,
      "variants": 3,
      "props": [
        {
          "prop": "Property 1",
          "values": [
            "Disable",
            "Primary",
            "Secondary"
          ]
        }
      ]
    },
    {
      "name": "Carousel Pager",
      "internal": false,
      "variants": 3,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "T0",
            "T1",
            "T1/2"
          ]
        }
      ]
    },
    {
      "name": ".Label",
      "internal": true,
      "variants": 2,
      "props": [
        {
          "prop": "Style",
          "values": [
            "Bold",
            "Default"
          ]
        }
      ]
    },
    {
      "name": "Member list element",
      "internal": false,
      "variants": 2,
      "props": [
        {
          "prop": "Break",
          "values": [
            "False",
            "True"
          ]
        }
      ]
    },
    {
      "name": "Member List",
      "internal": false,
      "variants": 2,
      "props": [
        {
          "prop": "Variant",
          "values": [
            "Default",
            "Max"
          ]
        }
      ]
    },
    {
      "name": "_Header",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Color",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Validation message",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Iconly",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Login",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Static - Carousel 1",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Video - Carousel",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Testimonial - Grid",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Component 251",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Shop",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Static - Carousel 2",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Individual video",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "Timeline",
      "internal": false,
      "variants": 1,
      "props": []
    },
    {
      "name": "FAQ - Mobile",
      "internal": false,
      "variants": 1,
      "props": []
    }
  ],
  "foreignLibraries": [
    "www.goodlifemeds.com",
    "neuracore.uprock.pro"
  ]
} as {
  counts: Record<string, number>
  colours: Swatch[]
  type: TypeStyle[]
  effects: EffectStyle[]
  variables: Token[]
  components: ComponentSet[]
  foreignLibraries: string[]
}
